config/routes.rb
Voutche::Application.routes.draw do

  resources :pages do
  end

  root to: 'pages#home'

  match '/about',   to: 'pages#about',  via: :get
  match '/help',    to: 'pages#help',   via: :get
  match '/contact', to: 'pages#contact', via: :get

  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]

  

end

app/models/user.rb
class User < ActiveRecord::Base

	def self.from_omniauth(auth)
	  where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
	    user.provider = auth.provider
	    user.uid = auth.uid
	    user.name = auth.info.name
	    user.oauth_token = auth.credentials.token
	    user.oauth_expires_at = Time.at(auth.credentials.expires_at)
	    user.save!
	  end
      
		def facebook
		  @facebook ||= Koala::Facebook::API.new(oauth_token)
		  block_given? ? yield(@facebook) : @facebook
		rescue Koala::Facebook::APIError => e
		  logger.info e.to_s
		  nil # or consider a custom null object
		end

		def friends_count
		  facebook { |fb| fb.get_connection("me", "friends").size }
		end      

	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


	private

	def current_user
	  @current_user ||= User.find(session[:user_id]) if session[:user_id]
	end
	helper_method :current_user

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def help
  end

  def contact
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_url
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Voutche", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to  "Home",    root_path %></li>
          <li><%= link_to "About",    about_path %></li>
          <li><%= link_to "Help",     help_path %></li>
          <li><%= link_to "Contact",  contact_path %></li>   
          <li>
              <% if current_user %>
                Signed in as <strong><%= current_user.name %></strong>!
                <%= link_to "Sign out", signout_path, id: "sign_out" %>
              <% else %>
                <%= link_to "Facebook Login", "/auth/facebook", id: "sign_in" %>
              <% end %>
            </li>                 
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= Voutche %></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    # <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About Uss</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/help.html.erb
<h1>Help</h1>
<p>The Help Page</p>

app/views/pages/home.html.erb
<div class="center hero-unit">

  <h1>Welcome to Voutche</h1>
  <p>Voutche is a security app for social media.</p>	

<%=	link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary" %>
</div>